const FEATURED_IDS = ["file-organizer", "weather", "hangman", "password-gen", "sysmon", "trivia-quiz"];

const SCRIPT_META = {
  "bulk-rename":         { difficulty: "beginner",      requires: [] },
  "img-crush":           { difficulty: "intermediate",  requires: ["Pillow"] },
  "csv-to-json":         { difficulty: "beginner",      requires: [] },
  "json-to-csv":         { difficulty: "beginner",      requires: [] },
  "duplicate-finder":    { difficulty: "intermediate",  requires: [] },
  "folder-size":         { difficulty: "beginner",      requires: [] },
  "pdf-merger":          { difficulty: "intermediate",  requires: ["pypdf"] },
  "text-search":         { difficulty: "beginner",      requires: [] },
  "sysmon":              { difficulty: "intermediate",  requires: ["psutil"] },
  "remind-me":           { difficulty: "beginner",      requires: [] },
  "password-gen":        { difficulty: "beginner",      requires: [] },
  "countdown-timer":     { difficulty: "beginner",      requires: [] },
  "net-scan":            { difficulty: "intermediate",  requires: [] },
  "weather":             { difficulty: "beginner",      requires: [] },
  "qr-gen":              { difficulty: "intermediate",  requires: ["qrcode", "Pillow"] },
  "ip-info":             { difficulty: "beginner",      requires: [] },
  "stopwatch":           { difficulty: "intermediate",  requires: [] },
  "unit-converter":      { difficulty: "beginner",      requires: [] },
  "clipboard-saver":     { difficulty: "intermediate",  requires: ["pyperclip"] },
  "auto-backup":         { difficulty: "beginner",      requires: [] },
  "file-organizer":      { difficulty: "beginner",      requires: [] },
  "screenshot-taker":    { difficulty: "intermediate",  requires: ["pyautogui"] },
  "email-sender":        { difficulty: "intermediate",  requires: [] },
  "rename-by-date":      { difficulty: "beginner",      requires: [] },
  "website-monitor":     { difficulty: "intermediate",  requires: [] },
  "webpage-to-pdf":      { difficulty: "beginner",      requires: [] },
  "broken-link-checker": { difficulty: "beginner",      requires: [] },
  "json-formatter":      { difficulty: "beginner",      requires: [] },
  "url-shortener":       { difficulty: "beginner",      requires: [] },
  "number-guesser":      { difficulty: "beginner",      requires: [] },
  "hangman":             { difficulty: "beginner",      requires: [] },
  "rock-paper-scissors": { difficulty: "beginner",      requires: [] },
  "trivia-quiz":         { difficulty: "beginner",      requires: [] },
  "word-scramble":       { difficulty: "intermediate",  requires: [] },
};
