const FEATURED_IDS = ["file-organizer","weather","hangman","password-gen","sysmon","trivia-quiz"];

const SCRIPT_META = {
  "bulk-rename":         { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "img-crush":           { difficulty:"intermediate", requires:["Pillow"],             version:"1.1" },
  "csv-to-json":         { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "json-to-csv":         { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "duplicate-finder":    { difficulty:"intermediate", requires:[],                    version:"1.0" },
  "folder-size":         { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "pdf-merger":          { difficulty:"intermediate", requires:["pypdf"],             version:"1.0" },
  "text-search":         { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "sysmon":              { difficulty:"intermediate", requires:["psutil"],            version:"1.2" },
  "remind-me":           { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "password-gen":        { difficulty:"beginner",     requires:[],                    version:"1.1" },
  "countdown-timer":     { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "net-scan":            { difficulty:"intermediate", requires:[],                    version:"1.0" },
  "weather":             { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "qr-gen":              { difficulty:"intermediate", requires:["qrcode","Pillow"],   version:"1.0" },
  "ip-info":             { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "stopwatch":           { difficulty:"intermediate", requires:[],                    version:"1.0" },
  "unit-converter":      { difficulty:"beginner",     requires:[],                    version:"1.1" },
  "clipboard-saver":     { difficulty:"intermediate", requires:["pyperclip"],         version:"1.0" },
  "auto-backup":         { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "file-organizer":      { difficulty:"beginner",     requires:[],                    version:"1.2" },
  "screenshot-taker":    { difficulty:"intermediate", requires:["pyautogui"],         version:"1.0" },
  "email-sender":        { difficulty:"intermediate", requires:[],                    version:"1.0" },
  "rename-by-date":      { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "website-monitor":     { difficulty:"intermediate", requires:[],                    version:"1.0" },
  "webpage-to-pdf":      { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "broken-link-checker": { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "json-formatter":      { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "url-shortener":       { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "number-guesser":      { difficulty:"beginner",     requires:[],                    version:"1.1" },
  "hangman":             { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "rock-paper-scissors": { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "trivia-quiz":         { difficulty:"beginner",     requires:[],                    version:"1.0" },
  "word-scramble":       { difficulty:"intermediate", requires:[],                    version:"1.0" },
};
